apiVersion: v1
kind: Service
metadata:
  name: taskqueue-service
spec:
  selector:
    app: taskqueue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
