basePath: /v1
definitions:
  shared.EnqueueSmsRequest:
    properties:
      phoneNumber:
        type: string
      smsBody:
        type: string
    required:
    - phoneNumber
    - smsBody
    type: object
  shared.EnqueueSmsResponse:
    properties:
      id:
        type: integer
      status:
        type: string
    type: object
  shared.SmsQueue:
    properties:
      createdDate:
        type: string
      id:
        type: integer
      phoneNumber:
        type: string
      smsBody:
        type: string
      status:
        type: string
      tryCount:
        type: integer
      userId:
        type: integer
    type: object
  shared.TriggerWorkerRequest:
    type: object
  shared.TriggerWorkerResponse:
    properties:
      handledSmsCount:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: This is a microservice server called TaskQueue, which provides various
    endpoints for managing tasks in a queue. It allows you to enqueue SMS messages,
    trigger workers for processing tasks, and retrieve SMS queue entries.
  title: TaskQueue API
  version: "1.0"
paths:
  /SmsQueue/Enqueue:
    post:
      consumes:
      - application/json
      description: This endpoint enqueues an SMS for processing in the task queue.
      parameters:
      - description: Request object for enqueuing an SMS
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/shared.EnqueueSmsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful response with details of the enqueued SMS
          schema:
            $ref: '#/definitions/shared.EnqueueSmsResponse'
        "400":
          description: Bad Request
      security:
      - BearerAuth: []
      summary: Enqueue SMS
      tags:
      - TaskQueue
  /SmsQueue/ReadAll:
    get:
      consumes:
      - application/json
      description: This endpoint retrieves all SMS queue entries.
      produces:
      - application/json
      responses:
        "200":
          description: List of SMS queue entries
          schema:
            items:
              $ref: '#/definitions/shared.SmsQueue'
            type: array
        "400":
          description: Bad Request
      security:
      - BearerAuth: []
      summary: Read All SMS Queue
      tags:
      - TaskQueue
  /SmsQueue/ReadAll/Fail:
    get:
      consumes:
      - application/json
      description: This endpoint retrieves all failed SMS queue entries.
      produces:
      - application/json
      responses:
        "200":
          description: List of failed SMS queue entries
          schema:
            items:
              $ref: '#/definitions/shared.SmsQueue'
            type: array
        "400":
          description: Bad Request
      security:
      - BearerAuth: []
      summary: Read All Failed SMS Queue Entries
      tags:
      - TaskQueue
  /SmsQueue/TriggerWorker:
    post:
      consumes:
      - application/json
      description: This endpoint triggers a worker for processing tasks in the task
        queue.
      parameters:
      - description: Request object for triggering a worker
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/shared.TriggerWorkerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful response with details of worker execution
          schema:
            $ref: '#/definitions/shared.TriggerWorkerResponse'
        "400":
          description: Bad Request
      security:
      - BearerAuth: []
      summary: Trigger Worker
      tags:
      - TaskQueue
securityDefinitions:
  BearerAuth:
    description: Please include a valid bearer token in the 'Authorization' header
      for authentication.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
